# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/camcv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/camcv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/camcv/CMakeFiles /home/pi/camcv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/camcv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named camcv

# Build rule for target.
camcv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 camcv
.PHONY : camcv

# fast build rule for target.
camcv/fast:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/build
.PHONY : camcv/fast

RaspiCam/RaspiCLI.o: RaspiCam/RaspiCLI.c.o
.PHONY : RaspiCam/RaspiCLI.o

# target to build an object file
RaspiCam/RaspiCLI.c.o:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/RaspiCam/RaspiCLI.c.o
.PHONY : RaspiCam/RaspiCLI.c.o

RaspiCam/RaspiCLI.i: RaspiCam/RaspiCLI.c.i
.PHONY : RaspiCam/RaspiCLI.i

# target to preprocess a source file
RaspiCam/RaspiCLI.c.i:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/RaspiCam/RaspiCLI.c.i
.PHONY : RaspiCam/RaspiCLI.c.i

RaspiCam/RaspiCLI.s: RaspiCam/RaspiCLI.c.s
.PHONY : RaspiCam/RaspiCLI.s

# target to generate assembly for a file
RaspiCam/RaspiCLI.c.s:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/RaspiCam/RaspiCLI.c.s
.PHONY : RaspiCam/RaspiCLI.c.s

RaspiCam/RaspiCamControl.o: RaspiCam/RaspiCamControl.c.o
.PHONY : RaspiCam/RaspiCamControl.o

# target to build an object file
RaspiCam/RaspiCamControl.c.o:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/RaspiCam/RaspiCamControl.c.o
.PHONY : RaspiCam/RaspiCamControl.c.o

RaspiCam/RaspiCamControl.i: RaspiCam/RaspiCamControl.c.i
.PHONY : RaspiCam/RaspiCamControl.i

# target to preprocess a source file
RaspiCam/RaspiCamControl.c.i:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/RaspiCam/RaspiCamControl.c.i
.PHONY : RaspiCam/RaspiCamControl.c.i

RaspiCam/RaspiCamControl.s: RaspiCam/RaspiCamControl.c.s
.PHONY : RaspiCam/RaspiCamControl.s

# target to generate assembly for a file
RaspiCam/RaspiCamControl.c.s:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/RaspiCam/RaspiCamControl.c.s
.PHONY : RaspiCam/RaspiCamControl.c.s

RaspiCam/RaspiPreview.o: RaspiCam/RaspiPreview.c.o
.PHONY : RaspiCam/RaspiPreview.o

# target to build an object file
RaspiCam/RaspiPreview.c.o:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/RaspiCam/RaspiPreview.c.o
.PHONY : RaspiCam/RaspiPreview.c.o

RaspiCam/RaspiPreview.i: RaspiCam/RaspiPreview.c.i
.PHONY : RaspiCam/RaspiPreview.i

# target to preprocess a source file
RaspiCam/RaspiPreview.c.i:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/RaspiCam/RaspiPreview.c.i
.PHONY : RaspiCam/RaspiPreview.c.i

RaspiCam/RaspiPreview.s: RaspiCam/RaspiPreview.c.s
.PHONY : RaspiCam/RaspiPreview.s

# target to generate assembly for a file
RaspiCam/RaspiPreview.c.s:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/RaspiCam/RaspiPreview.c.s
.PHONY : RaspiCam/RaspiPreview.c.s

mycamera.o: mycamera.c.o
.PHONY : mycamera.o

# target to build an object file
mycamera.c.o:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/mycamera.c.o
.PHONY : mycamera.c.o

mycamera.i: mycamera.c.i
.PHONY : mycamera.i

# target to preprocess a source file
mycamera.c.i:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/mycamera.c.i
.PHONY : mycamera.c.i

mycamera.s: mycamera.c.s
.PHONY : mycamera.s

# target to generate assembly for a file
mycamera.c.s:
	$(MAKE) -f CMakeFiles/camcv.dir/build.make CMakeFiles/camcv.dir/mycamera.c.s
.PHONY : mycamera.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... camcv"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RaspiCam/RaspiCLI.o"
	@echo "... RaspiCam/RaspiCLI.i"
	@echo "... RaspiCam/RaspiCLI.s"
	@echo "... RaspiCam/RaspiCamControl.o"
	@echo "... RaspiCam/RaspiCamControl.i"
	@echo "... RaspiCam/RaspiCamControl.s"
	@echo "... RaspiCam/RaspiPreview.o"
	@echo "... RaspiCam/RaspiPreview.i"
	@echo "... RaspiCam/RaspiPreview.s"
	@echo "... mycamera.o"
	@echo "... mycamera.i"
	@echo "... mycamera.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

